name: Deploy Frontend (ByetHost)

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: FTP Deploy to ByetHost
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          local-dir: ./frontend/
          server: ${{ secrets.FRONTEND_FTP_SERVER }}
          username: ${{ secrets.FRONTEND_FTP_USERNAME }}
          password: ${{ secrets.FRONTEND_FTP_PASSWORD }}
          protocol: ftp
          server-dir: /htdocs/
          port: 21

          dangerous-clean-slate: false
