name: Deploy Frontend to Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Upload Frontend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FRONTEND_FTP_SERVER }}
          username: ${{ secrets.FRONTEND_FTP_USERNAME }}
          password: ${{ secrets.FRONTEND_FTP_PASSWORD }}

          local-dir: frontend/
          server-dir: /public_html/
